compile:
	gcc -Wall -g3 -fsanitize=address -pthread SNCServer.c -o server -std=c99
	gcc -Wall -g3 -fsanitize=address -pthread SNCclient.c -o client -std=c99
FLAGS    = -L /lib64
LIBS     = -lusb-1.0 -l pthread
